name: Deploy to GitHub Pages

concurrency:
  group: ${{ github.workflow }}

on:
  push:
    tags:
      - v*
    paths-ignore:
      - .gitignore
      - CONTRIBUTING.md
      - README.md
      - TODO

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment: prod

    steps:
      - name: Checkout # for firebase.json
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy
        uses: w9jds/firebase-action@v13.8.0
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
