name: Deploy to GitHub Pages

concurrency:
  group: ${{ github.workflow }}

on:
  push:
    tags:
      - v*
    paths-ignore:
      - 'README.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
